apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  labels:
    app: blue-webserver
  namespace: blue-green-app
spec:
  type: NodePort
  selector:
    app: webserver
    ver: {{ .Values.serviceSelectorColor }}    # either "blue" or "green"
  ports:
    - protocol: TCP
      nodePort: 30010
      port: 80
      targetPort: 80
