serviceSelectorColor: blue

service:
  type: NodePort
  port: 8080
  nodePort: 30010

blue:
  replicaCount: 4
  image:
    repository: eyesoncloud/web-app
    tag: v1
  extraVolumeMounts:
    - name: nginx-temp
      mountPath: /var/cache/nginx
  securityContext:
    runAsUser: 1001
    runAsGroup: 0
    fsGroup: 1001
  volumes:
    - name: nginx-temp
      emptyDir: {}

green:
  replicaCount: 3
  image:
    repository: eyesoncloud/web-app
    tag: v2
  extraVolumeMounts:
    - name: nginx-temp
      mountPath: /var/cache/nginx
  securityContext:
    runAsUser: 1001
    runAsGroup: 0
    fsGroup: 1001
  volumes:
    - name: nginx-temp
      emptyDir: {}
