blue:
  replicaCount: 4
  image:
    repository: eyesoncloud/web-app
    tag: v1
  ingress:
    enabled: false
  securityContext:
    runAsUser: 1001         
    runAsGroup: 0
    fsGroup: 1001           
  extraVolumeMounts:
    - name: nginx-temp
      mountPath: /var/cache/nginx
green:
  replicaCount: 3
  image:
    repository: eyesoncloud/web-app
    tag: v2
  ingress:
    enabled: false
  securityContext:
    runAsUser: 1001
    runAsGroup: 0
    fsGroup: 1001
  extraVolumeMounts:
    - name: nginx-temp
      mountPath: /var/cache/nginx

serviceSelectorColor: blue
service:
  type: NodePort
  nodePort: 30010
  port: 80

volumes:
  - name: nginx-temp
    emptyDir: {} 
